# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5891e09480d6648e2dda502084545792d3231986626f28356186ed12de42bb44277f4498181b046a73e9cd3bf2de0b8059c01bbfda63d95fcf22db68e2a5f09

test:
  secret_key_base: 761e56a49c0548a7f4d0bd5e7a48026bac64a7327e81d923d1ec49a63b1581487762567d1da20a1ae2a1c50c1a044bec18024a20e3b41dd5f32d8d23b445a02e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
